title: Henry Orton
description: My Personal Website
author: Dr Henry Orton
logo: /static/img/avatar.jpg
github: https://github.com/henryorton
about: Research Chemist

baseurl: ""
url: ""

allowsearch: true

# disqus_shortname: null
# google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
